model:
  size: x
  device: "cuda"
# for the inference img size, bigger should be better, for the previous MCMT WP, i am using [1280,1280] 
inference_size: [ 1280, 1280 ]
classes: [ 2, 5, 7 ]
log_level: DEBUG
redis:
  host: redis
  port: 6379
  stream_ids:
    - stream1
    - stream2 