{{- with .Values.redisWriter }}
{{- if .enabled }}
{{- range .configs }}
{{- $instanceName := printf "redis-writer-%s" (lower .name) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $instanceName }}-config
data:
  settings.yaml: |
    {{- toYaml . | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}