backbone: 'resnet101_ibn_a'
reid_config:
  reid_size_test: [384, 384]
  reid_model_path: 'feature_extractor/reid_model/resnet101_ibn_a_3.pth'  # only one model is used 

log_level: DEBUG

redis:
  host: redis
  port: 6379
  stream_id: stream1
  input_stream_prefix: objectdetector
  output_stream_prefix: featureextractor

prometheus_port: 8000
