version: '3.8'
services:
  redis:
    image: redis:7.0
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: "[ \"$(redis-cli ping)\" = \"PONG\" ] && exit 0 || exit 1"
      interval: 1s
      start_period: 5s

  local-sae-writer1:
    image: sirirouser/local_sae_writer_arm64:latest
    volumes:
      - ./local-sae-writer/local-sae-writer1.settings.yaml:/code/settings.yaml
      - ./local-sae-writer/saedumps/cityflow_cam041_new.saedump:/code/cityflow_cam041.saedump
    depends_on:
      redis:
        condition: service_healthy

  local-sae-writer2:
    image: sirirouser/local_sae_writer_arm64:latest
    volumes:
      - ./local-sae-writer/local-sae-writer2.settings.yaml:/code/settings.yaml
      - ./local-sae-writer/saedumps/cityflow_cam042_new.saedump:/code/cityflow_cam042.saedump
    depends_on:
      redis:
        condition: service_healthy

  local-sae-writer3:
    image: sirirouser/local_sae_writer_arm64:latest
    volumes:
      - ./local-sae-writer/local-sae-writer3.settings.yaml:/code/settings.yaml
      - ./local-sae-writer/saedumps/cityflow_cam043_new.saedump:/code/cityflow_cam043.saedump
    depends_on:
      redis:
        condition: service_healthy

  local-sae-writer4:
    image: sirirouser/local_sae_writer_arm64:latest
    volumes:
      - ./local-sae-writer/local-sae-writer4.settings.yaml:/code/settings.yaml
      - ./local-sae-writer/saedumps/cityflow_cam044_new.saedump:/code/cityflow_cam044.saedump
    depends_on:
      redis:
        condition: service_healthy

  local-sae-writer5:
    image: sirirouser/local_sae_writer_arm64:latest
    volumes:
      - ./local-sae-writer/local-sae-writer5.settings.yaml:/code/settings.yaml
      - ./local-sae-writer/saedumps/cityflow_cam045_new.saedump:/code/cityflow_cam045.saedump
    depends_on:
      redis:
        condition: service_healthy

  local-sae-writer6:
    image: sirirouser/local_sae_writer_arm64:latest
    volumes:
      - ./local-sae-writer/local-sae-writer6.settings.yaml:/code/settings.yaml
      - ./local-sae-writer/saedumps/cityflow_cam046_new.saedump:/code/cityflow_cam046.saedump
    depends_on:
      redis:
        condition: service_healthy