version: '3.8'
services:
  redis:
    image: redis:7.0
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: "[ \"$(redis-cli ping)\" = \"PONG\" ] && exit 0 || exit 1"
      interval: 1s
      start_period: 5s

  # streaming-server:
  #   image: bluenviron/mediamtx:latest-ffmpeg   # multi-arch tag
  #   platform: "linux/arm64" # Specify the platform to ensure compatibility
  #   volumes:
  #     - ./streaming-server/mediamtx.yml:/mediamtx.yml
  #     - ${VIDEO_PATH4}:/video4
  #   environment:
  #     MTX_PROTOCOLS: tcp
  #   ports:
  #     - 8554:8554

  video-source-stream3:
    image: mcvt_yq/video_source_py_arm64:eval
    environment:
      - VIDEO_SOURCE_PARALLELISM=2
    volumes:
      - ./video-source-py/video-source-stream3.settings.yaml:/code/settings.yaml
      - /home/yuqiang/yl4300/Multi-Camera-Vision-Pipeline-YQ/carmel_data/cam03_2k_15fps.mp4:/code/cam03_2k_15fps.mp4
    depends_on:
      redis:
        condition: service_healthy

  object-detector3:
    image: sirirouser/object_detector_arm64:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all    
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia  # Ensure NVIDIA runtime is used
    volumes:
      - ./object-detector/object-detector3.settings.yaml:/code/settings.yaml  # Config file
      - /home/yuqiang/yl4300/Multi-Camera-Vision-Pipeline-YQ/subpackages/object-detector-YQ/object-detector-YQ/yolo11m_cuda.engine:/code/yolo11m.engine  # NOTE: Regarding the engine file, try a different way to generate the TRT file, the yolov11l.engine looks better than other .engine file.

    depends_on:
      redis:
        condition: service_healthy

  object-tracker-stream3:
    image: sirirouser/object_tracker_arm64:latest
    volumes:
      - ./object-tracker/object-tracker-stream3.settings.yaml:/code/settings.yaml
      - ./object-tracker/tracking_config/bytetrack.yaml:/code/tracking_config/bytetrack.yaml
      - ./object-tracker/reid_weights/clip_vehicleid.pt:/code/clip_vehicleid.pt
    depends_on:
      redis:
        condition: service_healthy

  geo-mapper3:
    image: sirirouser/geomapper_arm64:latest
    volumes:
      - ./geo-mapper/geo-mapper3.settings.yaml:/code/settings.yaml
      - ./geo-mapper/cam_config/cam03_fitted_cam.json:/code/cam03.json
    depends_on:
      redis:
        condition: service_healthy
  
  feature_extractor3:
    image: sirirouser/feature_extractor_arm64:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all    
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia  # Ensure NVIDIA runtime is used
    volumes:
      - ./feature-extractor/feature-extractor3.settings.yaml:/code/settings.yaml
      - ./feature-extractor/model_config/model_config.yaml:/code/model_config.yaml
      - ./feature-extractor/model_config/sbs_model.pth:/code/sbs_model.pth
    depends_on:
      redis:
        condition: service_healthy
  
  # redis-writer:
  #   image: sirirouser/redis_writer_arm64:latest
  #   volumes:
  #     - ./redis-writer/redis-writer.settings.yaml:/code/settings.yaml
  #   depends_on:
  #     redis:
  #       condition: service_healthy