version: '3.8'
services:
  redis:
    image: redis:7.0
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: "[ \"$(redis-cli ping)\" = \"PONG\" ] && exit 0 || exit 1"
      interval: 1s
      start_period: 5s

  local-sae-writer1:
    image: sirirouser/local_sae_writer_arm64:latest
    volumes:
      - ./local-sae-writer/local-sae-writer1.settings.yaml:/code/settings.yaml
      - ./local-sae-writer/saedumps/cam01_new.saedump:/code/cam01.saedump
    depends_on:
      redis:
        condition: service_healthy

  local-sae-writer2:
    image: sirirouser/local_sae_writer_arm64:latest
    volumes:
      - ./local-sae-writer/local-sae-writer2.settings.yaml:/code/settings.yaml
      - ./local-sae-writer/saedumps/cam02_new.saedump:/code/cam02.saedump
    depends_on:
      redis:
        condition: service_healthy

  local-sae-writer3:
    image: sirirouser/local_sae_writer_arm64:latest
    volumes:
      - ./local-sae-writer/local-sae-writer3.settings.yaml:/code/settings.yaml
      - ./local-sae-writer/saedumps/cam03_new.saedump:/code/cam03.saedump
      # - /home/yuqiang/yl4300/Multi-Camera-Vision-Pipeline-YQ/tools/sae-introspection/record_saedump/featureextractor_stream3.saedump:/code/cam03_sample.saedump
    depends_on:
      redis:
        condition: service_healthy

  local-sae-writer4:
    image: sirirouser/local_sae_writer_arm64:latest
    volumes:
      - ./local-sae-writer/local-sae-writer4.settings.yaml:/code/settings.yaml
      - ./local-sae-writer/saedumps/cam04_new.saedump:/code/cam04.saedump
      # - /home/yuqiang/yl4300/Multi-Camera-Vision-Pipeline-YQ/tools/sae-introspection/record_saedump/featureextractor_stream4.saedump:/code/cam04_sample.saedump
    depends_on:
      redis:
        condition: service_healthy