tracker_algorithm: DEEPSORT
tracker_config:
    max_cosine_distance: 0.2
    min_confidence: 0.2
    max_iou_distance: 0.7
    max_age: 30
    n_init: 1 # change in DeepSort, it is meaningless to setup this value in here. 
    multi_camera_tracking: TRUE

log_level: DEBUG

redis:
  host: redis  # Updated to point to localhost
  port: 6379
  stream_id: stream2
  input_stream_prefix: featureextractor
  output_stream_prefix: objecttracker
