id: stream2
uri: rtsp://streaming-server:8554/video-stream2
mask: True
mask_polygon_location: /code/points_SB.txt
reconnect_backoff_time: 1
max_fps: 10
jpeg_encode: True
log_level: DEBUG
redis:
  host: redis
  port: 6379