id: stream1
uri: rtsp://streaming-server:8554/video-stream1
mask: True
mask_polygon_location: /code/points_NB.txt
reconnect_backoff_time: 1
max_fps: 10
jpeg_encode: True
log_level: DEBUG
redis:
  host: redis
  port: 6379