paths:
  # video-stream1:
  #   runOnDemand: ffmpeg -re -stream_loop -1 -i /video1 -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
  #   runOnDemandRestart: yes

  video-stream2:
    runOnDemand: /bin/sh -c "sleep $(expr $(date -d '16:24:00' +%s) - $(date +%s)) && ffmpeg -re -stream_loop -1 -i /video2 -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH"
    runOnDemandRestart: yes